apps/products/urls.py
from django.urls import path
from apps.products.views import TagCreateView, TagListView, TagDetailView, TagUpdateView, TagDeleteView, create_tag

app_name = "products"


urlpatterns = [
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/<int:pk>/", TagDetailView.as_view(), name="tag-detail"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    # path("tags/create/", create_tag, name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="task-type-delete"),
]

forms/urls.py
from django.contrib import admin
from django.urls import path, include
from forms import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.products.urls", namespace="products")),
    path("", include("apps.users.urls", namespace="users")),
]

if not settings.TESTING:
    from debug_toolbar.toolbar import debug_toolbar_urls

    urlpatterns = [*urlpatterns] + debug_toolbar_urls()

apps/products/models.py
from django.db import models
from apps.products.abstract_models import BaseModel
from django.utils.translation import gettext_lazy as _


class Category(BaseModel):
    name = models.CharField(max_length=255, unique=True, verbose_name="Category Name")
    slug = models.SlugField(unique=True, verbose_name="Category Slug")
    description = models.TextField(blank=True, verbose_name="Category Description")
    image = models.ImageField(blank=True, upload_to="category/", verbose_name="Category Image")

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Tag(BaseModel):
    name = models.CharField(max_length=255, unique=True, verbose_name="Tag Name")
    slug = models.SlugField(unique=True, verbose_name="Tag Slug")

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")

    def __str__(self) -> str:
        return self.name


class Product(BaseModel):
    name = models.CharField(max_length=255, verbose_name="Product Name")
    description = models.TextField(blank=True, verbose_name="Product Description")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Product Price")
    image = models.ImageField(blank=True, upload_to="product/", verbose_name="Product Image")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Category", related_name="products")
    tags = models.ManyToManyField(Tag, verbose_name="Tags", related_name="products")

    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name

apps/products/forms.py
from django import forms
from apps.products.models import Tag


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = "__all__"


class TagUnboundedForm(forms.Form):
    name = forms.CharField(initial="www", label="Name))))", widget=forms.TextInput(attrs={"class": "form-control"}), required=False)
    slug = forms.CharField(max_length=1, label="Slug", empty_value="9", required=False)

apps/products/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from apps.products.forms import TagForm, TagUnboundedForm
from apps.products.models import Tag


# def create_tag(request):
#     if request.method == "POST":
#         form = TagUnboundedForm(request.POST)
#
#         # print(form.is_valid())
#         # print(form.is_valid())
#         # print(form.cleaned_data)
#         # print(form.as_table())
#         # print(form.base_fields["name"].label)
#         # print(form.fields["name"].label)
#         # print(form.get_context())
#         # print("data", form.data)
#         # form.is_valid()
#         # print("cleaned_data", form.cleaned_data)
#         # print(form.template_name)
#         # print("instance", form.instance)
#         # print("initial", form.initial)
#
#         print(form.data)
#
#
#
#         if form.is_valid():
#             return HttpResponse("Tag was created successfully")
#             # return HttpResponseRedirect(reverse("products:tag-list"))
#     form = TagUnboundedForm()
#     return render(request, "products/tag_form.html", context={"form": form})


def create_tag(request):
    if request.method == "POST":
        form = TagForm(request.POST)

        # print(form.errors)
        # print(form.is_valid())
        # print(form.cleaned_data)
        # print(form.as_table())
        # print(form.base_fields["name"].label)
        # print(form.fields["name"].label)
        # print(form.get_context())
        # print("data", form.data)
        # form.is_valid()
        # print("cleaned_data", form.cleaned_data)
        # print(form.template_name)
        # print("instance", form.instance)
        # print("initial", form.initial)

        # print(dir(form))



        if form.is_valid():
            form.save()
            return HttpResponse("Tag was created successfully")
            # return HttpResponseRedirect(reverse("products:tag-list"))
    form = TagForm()
    return render(request, "products/tag_form.html", context={"form": form})


class TagCreateView(LoginRequiredMixin, generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("products:tag-list")


class TagDetailView(LoginRequiredMixin, generic.DetailView):
    model = Tag


class TagListView(LoginRequiredMixin, generic.ListView):
    model = Tag
    paginate_by = 20


class TagUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("products:tag-list")


class TagDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("products:tag-list")

templates/products/tag_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <h1>Delete Tag</h1>
  <p>Are you sure you want to delete the tag: {{ tag }}?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete!" class="btn btn-danger">
  </form>
{% endblock %}

templates/products/tag_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Name: {{ tag.name }}</h1>
  <div class="ml-3">
    <h3>Tags:</h3>
    {% for worker in position.workers.all %}
      <hr>
      <p class="text-muted">
        <strong>Username:</strong>
        {{ worker.username }}
        <br>
        <strong>Full name:</strong>
        {{ worker.first_name }} {{ worker.last_name }}
        <br>
        <strong>Email:</strong>
        {{ worker.email }}
        <br>
        <strong>Active:</strong>
        {{ worker.print_active }}
        <br>
        <strong>Date of employment:</strong>
        {{ worker.date_joined }}
        </p>
    {% empty %}
      <p>No workers!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/products/tag_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form }}

{#    {{ form.as_ul }}#}
{#    {{ form.as_p }}#}
{#    {{ form.name.value }}#}
{#    {{ form.name.value }}#}

    <input type="submit" value="Submit" class="btn btn-dark">
  </form>
{% endblock %}

templates/products/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tag List
    <a style="float: right" class="btn btn-secondary text-white" href="{% url 'products:tag-create' %}">Create</a>
  </h1>
   <form  action="" method="get" class="text-white">
    {{ search_form.name }}
    <input type="submit" value="🔎" class="btn btn-outline-light">
  </form>
  {% if position_list %}
    <table class="table text-bold">
      <tr>
        <th>ID</th>
        <th>NAME</th>
        <th>UPDATE</th>
        <th>DELETE</th>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>
            {{ tag.id }}
          </td>
          <td>
            <a href="{% url 'products:tag-detail' pk=tag.id %}">{{ tag.name }}</a>
          </td>
{#          <td>#}
{#            <a href="{% url 'company:position-update' pk=position.pk %}">Update</a>#}
{#          </td>#}
{#          <td>#}
{#            <a href="{% url 'company:position-delete' pk=position.pk %}">Delete</a>#}
{#          </td>#}
        </tr>
      {% endfor %}

    </table>
  {% else  %}
    <p>There are not tags in products</p>
  {% endif %}
{% endblock %}